---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
library(data.table)
if(!file.exists("activity.csv")){
    unzip('activity.zip')
}
activityData <- data.table(read.csv("activity.csv"))
```


## What is mean total number of steps taken per day?

```{r}
totalSteps <- activityData[complete.cases(activityData),.(total_steps=sum(steps)),by=.(date)]
totalSteps
```
HISTOGRAM
```{r} 
hist(totalSteps$total_steps,col="blue",xlab="Total Steps",main="Histogram of Steps")
```
MEAN
```{r}
mean(totalSteps$total_steps)
median(totalSteps$total_steps)
```


## What is the average daily activity pattern?

```{r}
meanSteps <- activityData[complete.cases(activityData),.(step_mean=mean(steps)),by=.(interval)]
```

HISTOGRAM
```{r}
plot(meanSteps,type='l')
```

AVG MAX STEPS
```{r }
meanSteps[step_mean==max(meanSteps$step_mean),]$interval
```


## Imputing missing values
```{r}
sum(is.na(activityData))
```

```{r}
activityData$steps[is.na(activityData$steps)] <- mean(activityData$steps,na.rm=TRUE)
activityData$steps <- as.numeric(activityData$steps)
activityData$interval <- as.numeric(activityData$interval)
colSums(is.na(activityData))
```

```{r}
summary(activityData)
```

```{r}
hist(activityData[,sum(steps),by=date]$V1,col="blue",main="Histogram of Steps with Imputed Values", xlab="Total Steps")
```

```{r}
mean(activityData[,sum(steps),by=date]$V1)
median(activityData[,sum(steps),by=date]$V1)
```

```{r}
mean(totalSteps$total_steps)
median(totalSteps$total_steps)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
activityData[, date := as.POSIXct(date, format = "%Y-%m-%d")]
activityData[, `Day of Week`:= weekdays(x = date)]
activityData[grepl(pattern = "Monday|Tuesday|Wednesday|Thursday|Friday", x = `Day of Week`), "weekday or weekend"] <- "weekday"
activityData[grepl(pattern = "Saturday|Sunday", x = `Day of Week`), "weekday or weekend"] <- "weekend"
activityData[, `weekday or weekend` := as.factor(`weekday or weekend`)]
head(activityData, 10)
```

```{r}
activityData[is.na(steps), "steps"] <- activityData[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
IntervalData <- activityData[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval, `weekday or weekend`)] 
```

```{r}
library(ggplot2)
ggplot(IntervalData , aes(x = interval , y = steps, color=`weekday or weekend`)) + geom_line() + labs(title = "Avg. Daily Steps by Weektype", x = "Interval", y = "No. of Steps") + facet_wrap(~`weekday or weekend` , ncol = 1, nrow=2)
```